# -*- coding: utf-8 -*-
#
# Copyright (C) 2020 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

version: "2.3"
services:
  mysql:
    image: mysql:${MYSQL_VERSION}
    restart: "always"
    environment:
      - "MYSQL_ROOT_PASSWORD=testrootpsw"
      - "MYSQL_DATABASE=invenio"
      - "MYSQL_USER=testuser"
      - "MYSQL_PASSWORD=testpsw"
    ports:
      - "3306:3306"
  postgresql:
    image: postgres:${POSTGRESQL_VERSION}
    restart: "always"
    environment:
      - "POSTGRES_USER=testuser"
      - "POSTGRES_PASSWORD=testpsw"
      - "POSTGRES_DB=invenio"
    ports:
      - "5432:5432"
